// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlPgX6LxbrEyaKvPETJVSn1X-_sVbjNwo',
    appId: '1:168353549537:web:5634eadb24147b17cb3ba0',
    messagingSenderId: '168353549537',
    projectId: 'personal-finance-tracker-f6e06',
    authDomain: 'personal-finance-tracker-f6e06.firebaseapp.com',
    storageBucket: 'personal-finance-tracker-f6e06.firebasestorage.app',
    measurementId: 'G-ESNP5LGQR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGVbuB3KpNSAPIerQcasm52g0FK_fcdIo',
    appId: '1:168353549537:android:dc322c3eb63e875acb3ba0',
    messagingSenderId: '168353549537',
    projectId: 'personal-finance-tracker-f6e06',
    storageBucket: 'personal-finance-tracker-f6e06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3mC5Hcb-uuT9vCOMhioXpVVcag6cAXI',
    appId: '1:168353549537:ios:3f18c40b4980b38ecb3ba0',
    messagingSenderId: '168353549537',
    projectId: 'personal-finance-tracker-f6e06',
    storageBucket: 'personal-finance-tracker-f6e06.firebasestorage.app',
    iosBundleId: 'com.group.personalfinancetracker.personalFinanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA3mC5Hcb-uuT9vCOMhioXpVVcag6cAXI',
    appId: '1:168353549537:ios:3f18c40b4980b38ecb3ba0',
    messagingSenderId: '168353549537',
    projectId: 'personal-finance-tracker-f6e06',
    storageBucket: 'personal-finance-tracker-f6e06.firebasestorage.app',
    iosBundleId: 'com.group.personalfinancetracker.personalFinanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlPgX6LxbrEyaKvPETJVSn1X-_sVbjNwo',
    appId: '1:168353549537:web:36207472ea979f79cb3ba0',
    messagingSenderId: '168353549537',
    projectId: 'personal-finance-tracker-f6e06',
    authDomain: 'personal-finance-tracker-f6e06.firebaseapp.com',
    storageBucket: 'personal-finance-tracker-f6e06.firebasestorage.app',
    measurementId: 'G-PBZH6DCG64',
  );

}