// lib/main.dart
// This file is the entry point of the Flutter application.
// It sets up the MaterialApp and defines the application's routes.

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import firebase_core
import 'firebase_options.dart'; // Import the generated firebase_options.dart file

// Import the custom splash_screen and login_screen widgets
import 'package:personal_finance_tracker/SplashScreen.dart';
import 'package:personal_finance_tracker/LoginScreen.dart';


// The main function is now asynchronous because Firebase.initializeApp() is an async operation.
void main() async {
  // Ensure that Flutter's binding is initialized before using plugins.
  // This is required for Firebase.initializeApp() to work correctly.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the options generated by FlutterFire CLI
  // for the current platform.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Personal Finance Tracker', // Changed title to be more relevant
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // Define the named routes for the application.
      // The initialRoute specifies which route to display first.
      initialRoute: '/',
      routes: {
        '/': (context) => const SplashScreen(), // The splash screen
        '/login': (context) => const LoginScreen(), // The login screen
      },
      debugShowCheckedModeBanner: false, // Hides the debug banner for a cleaner UI
    );
  }
}